var product=[{
"id":0,
"title":" ",
"brand":"",
"image":"No_Image_Available.jpg",
},{
"id":1,
"title":"boAt Rockerz 550",
"feature":"It support Bluetooth,It does not contain cable feature,It has Bluetooth 5.0,Light weighted Headphone (245g),Could have used a type-c port for charging",
"brand":"boAt",
"image":"1.jpg",
},{
"id":2,
"title":"JBL Tune 760NC",
"feature":"Active Noise Cancellation,Hands-free calls,JBL Pure Bass Soun,Voice Assistant support,Microphone Included,It support Bluetooth",
"brand":"JBL",
"image":"2.jpg",
},{
"id":3,
"title":" boAt Rockerz 450 ",
"feature":"It support Bluetooth.,It does not contain cable feature,It has Bluetooth 5.0,Light weighted Headphone (168g),Could have used a type-c port for charging",
"brand":"boAt",
"image":"3.jpg",
},{
"id":4,
"title":"Sony Wh-Ch510",
"feature":"Wireless,Bluetooth 5.0,Built-In mic,35 hours of battery life,A 10-minute quick charge with the Type-C cable will give you up to 90 minutes of play, Feel light on head(132g)",
"brand":"Sony",
"image":"4.jpg",
},{
"id":5,
"title":"boAt Rockerz 370",
"feature":"Android Phone Control,iOS Phone Control,Lightweight,Microphone Feature,Volume-Control",
"brand":"boAt",
"image":"6.jpg",
},{
"id":6,
"title":"boAt Rockerz 450 Pro",
"feature":"Android Phone Control,iOS Phone Control,Lightweight(168g),Microphone Feature,Volume-Control,The bass is tuned for a thumping experience that transports you to another world.",
"brand":"boAt",
"image":"7.jpg",
},{
"id":7,
"title":"ZEBRONICS Zeb-Duke1",
"feature":"Aux Cable Included,Call Function,Voice Assistant,Foldable",
"brand":"ZEBRONICS ",
"image":"8.jpg",
},{
"id":8,
"title":"EKSA E7000",
"feature":"It is with wire,It support Bluetooth,It is avaiable in different colour,Xbox One, PS4, PC, PS5, Mobile Devices,Gaming Headphones with Noise Cancelling Microphone,Comfortable Ear Pads",
"brand":"EKSA",
"image":"9.jpg",
},{
"id":9,
"title":"Jabra Gn Netcom Evolve 20",
"feature":"It is with wire,It support Bluetooth,It is avaiable in different colour,It is quite comfortable in your ear",
"brand":"Jabra",
"image":"10.jpg",
},{
"id":10,
"title":"Ambrane RangerZ",
"feature":"40mm Drivers with BoostedBass,Bluetooth V5.1,180° Rotatable,AUX & SD Card Support,Smart Buttons",
"brand":"Ambrane",
"image":"11.jpg",
},{
"id":11,
"title":"Boult Audio Probass Anchor",
"feature":"ANC,30 Hr Playtime,Voice assistant,Extra Bass,Comfort Fit,Superior Gaming Experience",
"brand":"Boult",
"image":"13.jpg",
},{
"id":12,
"title":"Hammer Bash 2.0",
"feature":" Sweatproof,Foldable,Big Battery,Super Comfy Design,Bluetooth v5.0,Deep bass,HD Sound,Combo of Aux Cable",
"brand":"Hammer",
"image":"14.jpg",
},{
"id":13,
"title":"Sony Extra Bass MDR-XB450AP",
"feature":"Noise cancelling,Water Resistant,BLuetooth & Aux Cable enabled Headphone,Padded Cushioning,Deep Bass,Voice Assistant,Tangle free cord",
"brand":"Sony",
"image":"15.jpg",
},{
"id":14,
"title":"Jabra Evolve2",
"feature":"Microphone,Wireless,Bluetooth 5.0,Built-In Mic,35 hours of battery life,A 10-minute quick charge with the Type-C cable will give you up to 90 minutes of play.",
"brand":"Jabra",
"image":"16.jpg",
},{
"id":15,
"title":"Tribit XFree",
"feature":"Wireless Bluetooth Headphone, HiFi Sound, Deep Bass,Lightweight,Type-C Lightening Fast Charge, Voice Control,Battery still works perfectly,  Sound quality is very good,Noise cancellation is awesome.",
"brand":"TRibit",
"image":"17.jpg",
},{
"id":16,
"title":"Infinity JBL Glide 510",
"feature":"72 Hrs Playtime with Quick Charge,Wireless On Ear Headphone with Mic,Deep Bass,Dual Equalizer,Bluetooth 5.0 with Voice Assistant Support",
"brand":"Infinity",
"image":"18.jpg",
},{
"id":17,
"title":"Bose Noise Cancelling 700",
"feature":"Noise Cancelling,Bluetooth,4 Mic,Mounting Hardware, USB Charging Cable,  Audio Cable",
"brand":"Bose",
"image":"19.jpg",
},{
"id":18,
"title":"Melomane Melophones Opera",
"feature":"Ultra Comfortable in wearing (Soft Earcups),400 mAh Lithium Big Battery (Standby Time 120 Hours),40mm HD Sound,ABS Plastic + TPE + Metal Body",
"brand":"Melomane",
"image":"20.jpg",
},{
"id":19,
"title":"pTron Studio",
"feature":"Lightweight Wireless Headset,Soft Cushions Earpads,Fast Charging & Aux Port",
"brand":"pTron",
"image":"21.jpg",
},{
"id":20,
"title":"ZEBRONICS Zeb-Bang",
"feature":"Wireless,Voice assistant support,AUX Function,Adjustable Headband,Media/Volume control,Call Function,Built-in Rechargeable Battery",
"brand":"ZEBRONICS",
"image":"22.jpg",
},{
"id":21,
"title":"MI Super Bass",
"feature":"Wireless,Voice assistant support,AUX Function,Adjustable Headband,Media/Volume control,Call Function,Built-in Rechargeable Battery",
"brand":"MI",
"image":"23.jpg",
},{
"id":22,
"title":"boAt BassHeads 900",
"feature":"Microphone,Lightweight,Perfect length cable",
"brand":"boAt",
"image":"24.jpg",
},{
"id":23,
"title":"YAMAHA Studio Monitor",
"feature":"Wireless,Microphone,Lightweight,Perfect length cable",
"brand":"YAMAHAL",
"image":"25.jpg",
},{
"id":24,
"title":"VEHOP Reason",
"feature":"Wireless,Tangle Free Cable+3.5mm Jack,Headset with 18hz-24Khz Frequency Response,Flexible Wired Headphone",
"brand":"VEHOP",
"image":"26.jpg",
},{
"id":25,
"title":"Sony WH-1000XM4C",
"feature":"Wireless,30 Hours Battery life,Quick Charge,AUX ,Touch Control and Voice Control,Noice cancellation",
"brand":"Sony",
"image":"27.jpg",
},{
"id":26,
"title":"Sony MDR-ZX110AP",
"feature":"30 Hours Battery life,Quick Charge,AUX ,Touch Control and Voice Control,Noice cancellation,Water Resistant,Padded Cushioning,Deep Bass,Voice Assistant",
"brand":"Sony",
"image":"28.jpg",
},{
"id":27,
"title":"Blaupunkt BH01",
"feature":"18 Hrs* Playtime,Passive Noise Reduction, TF Card Slot, Built-in FM, 40MM Drivers, Soft Padded Ear Cushions",
"brand":"Blaupunkt",
"image":"29.jpg",
},{
"id":28,
"title":"Audio-Technica Ath-M20X",
"feature":"xtreme battery life, Passive Noise Reduction,Built-in FM ,Soft Padded Ear Cushions",
"brand":"Audio",
"image":"30.jpg",
},{
"id":29,
"title":"Marshall Major IV ",
"feature":"Extreme battery life, Passive Noise Reduction, Built-in FM , Soft Padded Ear Cushions",
"brand":"Marshall",
"image":"31.jpg",
},{
"id":30,
"title":"Skullcandy Crusher Evo",
"feature":"Rapid Charge ,Personal Sound App, passive Noise Reduction,Soft Padded Ear Cushions",
"brand":"Skullcandy",
"image":"32.jpg",
},{
"id":31,
"title":"boAt Rockerz 510",
"feature":"Rapid Charge ,Personal Sound App ,Passive Noise Reduction, Soft Padded Ear Cushions",
"brand":"boAt",
"image":"33.jpg",
},{
"id":32,
"title":"boAt Rockerz 518",
"feature":"Rapid Charge ,Personal Sound App, passive Noise Reduction,Soft Padded Ear Cushions",
"brand":"boAt",
"image":"34.jpg",
},{
"id":33,
"title":"JBL Tune 500BT",
"feature":"JBL Pure Bass Sound,Dual Pairing,lightweight & Flat Foldable ,Less than 2 hours of charging for 100% battery, Get upto 1 hour of playback with 5mins of charging",
"brand":"JBL",
"image":"35.jpg",
},{
"id":34,
"title":"Philips Audio TAA4216",
"feature":"40 mm DriversQuick Charging,35 Hours Play Time,Cooling and Washable Ear Cups,IP55 Dust/Water Protection",
"brand":"Philips",
"image":"36.jpg",
},{
"id":35,
"title":"Sennheiser HD 458",
"feature":"Alexa Built-in,Active Noise Cancellation,30-Hour Battery life, USB-C Fast Charging",
"brand":"Sennheiser",
"image":"37.jpg",
},{
"id":36,
"title":"Sennheiser HD 450BT",
"feature":"Alexa Built-in,Active Noise Cancellation,30-Hour Battery life, USB-C Fast Charging",
"brand":"Sennheiser",
"image":"38.jpg",
},{
"id":37,
"title":"Philips Audio Upbeat Tauh201",
"feature":"Active Noise Cancellation,30-Hour Battery life,USB-C Fast Charging",
"brand":"Philips",
"image":"39.jpg",
},{
"id":38,
"title":"Philips Audio TAH6506BK/00",
"feature":"Active Noise Cancellation,30-Hour Battery life,USB-C Fast Charging",
"brand":"Philips",
"image":"40.jpg",
},{
"id":39,
"title":" Macmerise The Dark Knight ",
"feature":"10 Hours Playback,FM Radio,SD Card,Soft Padded Ear Cushions and Passive Noise Isolation,Decibel Wireless Headphone",
"brand":"Macmerise",
"image":"41.jpg",
},{
"id":40,
"title":"OneOdio Over Ear Headphones",
"feature":"50mm Driver,Foldable lightweight Headphones with Shareport, Mic for DJ Monitoring Mixing Guitar PC TV with microphone",
"brand":"OneOdio",
"image":"42.jpg",
},{
"id":41,
"title":"Sony WH-XB910N",
"feature":"Alexa Voice Control,Google Fast Pair,AUX & Swift Pair,30Hrs Battery life",
"brand":"Sony",
"image":"43.jpg",
},{
"id":42,
"title":"Redgear Cosmo 7",
"feature":"Active Noise Cancellation,30-Hour Battery life, USB-C Fast Charging",
"brand":"Redgear",
"image":"44.jpg",
},{
"id":43,
"title":"boAt Immortal IM 300",
"feature":"Volume Control,Dual Mics,Boom & Passive,Dual EQ Modes,3D Spatial & Music, Noise Isolating Earcups, 50MM Drivers ",
"brand":"boAt",
"image":"45.jpg",
},{
"id":44,
"title":" Cosmic Byte GS430",
"feature":"Volume Control,Dual Mics,Boom & Passive,Dual EQ Modes,3D Spatial & Music, Noise Isolating Earcups, 50MM Drivers ",
"brand":"Cosmic",
"image":"46.jpg",
},{
"id":45,
"title":"HyperX Cloud Stinger",
"feature":"Volume Control,10 Hours Playback,FM Radio,SD Card,Soft Padded Ear Cushions and Passive Noise Isolation,Decibel Wireless Headphone",
"brand":"HyperXr",
"image":"47.jpg",
},{
"id":46,
"title":" boAt Immortal IM1000D",
"feature":" 7.1 Channel Surround Audio,50mm Drivers, RGB Breathing LEDs",
"brand":"boAt",
"image":"48.jpg",
},{
"id":47,
"title":"Zebronics Jet PRO",
"feature":"Ear cup with LED lights,Extra soft ear cushion for comfort,Headband with LED lights,Powerful bass",
"brand":"Zebronics",
"image":"50.jpg",
},{
"id":48,
"title":"Ant Esports H1100 Pro",
"feature":"40Hrs Playtime,40mm Drivers,Punchy Bass,BT5.3,with Mic HD with ENC , Type-C Fast Charging",
"brand":"Ant Esports",
"image":"49.jpg",
},{
"id":49,
"title":"pTron Studio Pixel",
"feature":"40Hrs Playtime,40mm Drivers,Punchy Bass,BT5.3,with Mic HD with ENC , Type-C Fast Charging",
"brand":"pTron",
"image":"51.jpg",
},{
"id":50,
"title":"Zebronics Zeb-Blitz",
"feature":"RGB LED, Windows Software,Simulated 7.1 Surround Sound,2.4 Meter Braided Cable,Flexible mic, Ear Cushions with mic",
"brand":"Zebronics",
"image":"52.jpg",
},{
"id":51,
"title":"JBL Quantum 100",
"feature":"Designed for full compatibility with the native surround sound system,XboxTM ONE consoles.,Driver size: 40mm Dynamic drivers",
"brand":"JBL",
"image":"53.jpg",
},{
"id":52,
"title":"CHIPTRONEX Joker X",
"feature":"Designed for full compatibility with the native surround sound system,XboxTM ONE consoles.,Driver size: 40mm Dynamic drivers",
"brand":"Chiptronex",
"image":"54.jpg",
},{
"id":53,
"title":"HyperX Cloud Stinger 2 Core",
"feature":"Lightweight Over-Ear Headset with mic, Swivel-to-Mute Function, 40mm Drivers",
"brand":"HyperX",
"image":"55.jpg",
},{
"id":54,
"title":"Razer BlackShark V2 X",
"feature":" 7.1 Surround Sound,50mm Drivers-Memory, Foam Cushion-for PC,PS4,PS5, Switch,Xbox One,Xbox Series X|S,  Mobile-3.5mm Audio Jack",
"brand":"Razer",
"image":"56.jpg",
},{
"id":55,
"title":"Ant Esports H530",
"feature":"7.1 Surround Sound,50mm Drivers-Memory, Foam Cushion-for PC,PS4,PS5, Switch,Xbox One,Xbox Series X|S,  Mobile-3.5mm Audio Jack",
"brand":"Ant Esportr",
"image":"57.jpg",
},{
"id":56,
"title":"EKSA E800",
"feature":"Noise Canceltdng Mic,50mm Drivers ,LED light,Xbox One, Nintendo Switch,   VR with mic",
"brand":"EKSA",
"image":"58.jpg",
},{
"id":57,
"title":"HyperX Cloud Core",
"feature":"Noise Canceltdng Mic,50mm Drivers ,LED light,Xbox One, Nintendo Switch,   VR with mic",
"brand":"HyperX",
"image":"59.jpg",
},{
"id":58,
"title":"ZEBRONICS Zeb-8 BIT",
"feature":"50mm Drivers,Gaming Grade inbuilt mic , Radiating RGB Effect,  Dual 3.5mm Jack, 2.3m Durable Sleeved Cable,Suspended Headband and Volume Control",
"brand":"Zebronics",
"image":"60.jpg",
},{
"id":59,
"title":"Ant Esports H1150",
"feature":"50mm Drivers,Gaming Grade inbuilt mic ,Radiating RGB Effect,Dual 3.5mm Jack,2.3m Durable Sleeved Cable,Suspended Headband and Volume Control",
"brand":"Ant Esports",
"image":"61.jpg",
},{
"id":60,
"title":"Razer Barracuda X",
"feature":"USB-C Wireless Multi-Platform Connectivity,Wireless Multi-platform Gaming and Mobile Headset,Razer TriForce 40mm Drivers, Ultra-soft FlowKnit memory foam,Detachable HyperClear Cardioid",
"brand":"Razer",
"image":"62.jpg",
},{
"id":61,
"title":"ASTRO Gaming A50 (2019 Version) ",
"feature":"USB-C Wireless Multi-Platform Connectivity,Wireless Multi-platform Gaming and Mobile Headset,Razer TriForce 40mm Drivers, Ultra-soft FlowKnit memory foam,Detachable HyperClear Cardioid",
"brand":"Astro",
"image":"63.jpg",
},{
"id":62,
"title":"ZEBRONICS Crusher",
"feature":"Simulated Surround Sound,RGB LED,Powerful Bass , 2 Meter Braided Cable,  50mm Neodymium Drivers",
"brand":"Zebronics",
"image":"64.jpg",
},{
"id":63,
"title":"Gaming Headset K8",
"feature":" Simulated Surround SoundRGB LED,Powerful Bass , 2 Meter Braided Cable,50mm Neodymium Drivers",
"brand":"Gaming Headset ",
"image":"65.jpg",
},{
"id":64,
"title":"Logitech G335",
"feature":"Mic Flip to Mute 3.5Mm Audio Jack,Memory Foam Earpads,Compatible for PC,Playstation, Xbox,Nintendo Switch",
"brand":"Logitechr",
"image":"66.jpg",
},{
"id":65,
"title":"Cosmic Byte",
"feature":" 7.1 RGB,Dual Input USB,3.5mm Gaming Headset , Detachable Microphone for PC, Laptop, Mobiles, PS4, PS5,Xbox with Carrying case and Software",
"brand":"Cosmic",
"image":"67.jpg",
},{
"id":66,
"title":"boAt Immortal Im 1300",
"feature":"2.4Ghz Ultra Low Latency Mode Upto 35Ms, Bluetooth Mode 3D Spatial Audio,   Dual Mics,   Dongle Slot",
"brand":"boAt",
"image":"68.jpg",
},{
"id":67,
"title":"Logitech G Pro X",
"feature":"Blue Voice DTS Headphone,Blue Voice DTS Headphone,50Mm Pro-G Drivers, 2.0 Surround Sound for Esports Gaming, Pc/Ps/Xbox/Vr/Nintendo Switch",
"brand":"Logitech",
"image":"69.jpg",
},{
},{
"id":68,
"title":"Logitech G435 ",
"feature":"Blue Voice DTS Headphone,50Mm Pro-G Drivers,2.0 Surround Sound for Esports Gaming,Pc/Ps/Xbox/Vr/Nintendo Switch",
"brand":"Logitech",
"image":"70.jpg",
},{
"id":69,
"title":"Logitech G535 ",
"feature":"Lightweight on-Ear Headphones,flip to Mute mic,  Compatible with PC, PS4, PS5,USB Rechargeable",
"brand":"Logitech",
"image":"71.jpg",
},{
"id":70,
"title":"EKSA W1",
"feature":"7.1 Surround Sound,2 USB Ports,3 x 3.5mm Sockets,Best for PC, PS4, PS5, Xbox One",
"brand":"EKSA",
"image":"72.jpg",
},{
"id":71,
"title":"Corsair Hs35",
"feature":"7.1 Surround Sound,2 USB Ports,3 x 3.5mm Sockets,Best for PC, PS4, PS5, Xbox One",
"brand":"Corsair",
"image":"73.jpg",
},{
"id":72,
"title":"EKSA E900",
"feature":"Noise Cancetdng Mic,Detachable Headset, Compatible with PS4, PS5, PC, Laptop, One Key Mute Function",
"brand":"EKSA",
"image":"74.jpg",
},{
"id":73,
"title":"HyperX Cloud II Wired Over Ear Headphones",
"feature":"USB audio sound card with 7.1 virtual surround sound,53mm drivers neodymium magnets,Noise cancelling microphone via in-line sound card,Echo cancelling via in-line sound card,Compatible with PS4, PS5, PC, Laptop",
"brand":"HyperX",
"image":"75.jpg",
},{
"id":74,
"title":"Cosmic Byte G2050 ",
"feature":"Engaging in long hours of aggressive gaming is now comfortable.,soft & comfortable ear cups , braided cables and an amazingly flexible and auto-adjustable headband,Flaunt in Style Take your RGB Gaming experience up a notch with the true RGB colors.,G2050 microphone is made of a flexible, jelly-like material,Compatible with PS5 and PC.,7.1 Surround Sound",
"brand":"Cosmic",
"image":"76.jpg",
},{
"id":75,
"title":"boAt Immortal IM-200 7.1",
"feature":"Noise Cancetdng Mic,Detachable Headset, Compatible with PS4, PS5, PC, Laptop, One Key Mute Function",
"brand":"boAt",
"image":"77.jpg",
},{
"id":76,
"title":"Lenovo Ideapad H100",
"feature":"Engaging in long hours of aggressive gaming is now comfortable.,soft & comfortable ear cups , braided cables and an amazingly flexible and auto-adjustable headband,Flaunt in Style Take your RGB Gaming experience up a notch with the true RGB colors.,G2050 microphone is made of a flexible, jelly-like material,Compatible with PS5 and PC.,7.1 Surround Sound",
"brand":"Lenovo",
"image":"78.jpg",
},{
"id":77,
"title":"Sony INZONE H3",
"feature":"Over-Ear Headphones,360 Spatial Sound, USB Wired Over-Ear Professional,USB Connector,flip to Mute mic",
"brand":"Sony",
"image":"79.jpg",
},{
"id":78,
"title":"HP H200",
"feature":"Over-Ear Headphones, 360 Spatial Sound,USB Wired Over-Ear Professional,Mic/Compatible with PCs,Laptops,3.5mm Audio Output",
"brand":"HP",
"image":"80.jpg",
},{
    "id":79,
    "title":"Cosmic Byte Equinox Orion 7.1",
    "feature":"Over-Ear Headphones , 360 Spatial Sound , USB Wired Over-Ear Professional, Mic/Compatible with PCs,Laptops, 3.5mm Audio Output",
    "brand":"Cosmic",
    "image":"81.jpg",
},{
    "id":80,
    "title":"SteelSeries Arctis 7",
    "feature":" DTS Headphone Surround for PC,24 Hour Battery life ,ClearCast with Mic",
    "brand":"Steelseries",
    "image":"82.jpg",
},{
    "id":81,
    "title":"ASUS TUF H3",
    "feature":"50 mm ASUS Essence drivers and exclusive airtight chamber technology deliver an immersive audio experience,Virtual 7.1 surround sound supported by Windows Sonic,Tough, stainless-steel headband and yoke provide improved stability and durability,Lightweight design ensures comfort while gaming,Cross-platform support for PC, Mac, PS5, Nintendo Switch, Xbox One and mobile phones,Analog microphone provides clear in-game communication",
    "brand":"ASUS",
    "image":"84.jpg",
},{
    "id":82,
    "title":"SpinBot BattleBudz H1",
    "feature":"Large 50mm audio drivers produce great sound for a more immersive gaming experience.,Noise Canceltdng Adjustable Boom Mic makes sure you’re heard by gaming partners loud and clear.,Maximize the atmosphere of gaming with cool RGB LED lights,Connects to PC, mobile devices and game consoles via simple 3.5mm plug.,Premium memory protein ear pads and headband for comfortable gaming,2m long braided wire,On-Headset Volume Control",
    "brand":"SpinBot",
    "image":"85.jpg",
},{
    "id":83,
    "title":"Logitech G733",
    "feature":"Total freedom with up to 20 m wireless range,Lightweight wireless audio transmission.,Keep playing for up to 29 hours of battery life.,Colourful, reversible suspension headbands are designed for comfort during long play sessions.,Advanced mic filters that make your voice sound richer, cleaner, and more professional. ,Hear every audio cue with breathtaking clarity and get immerse in your game.",
    "brand":"Logitech",
    "image":"86.jpg",
},{
    "id":84,
    "title":"SteelSeries Arctis 3",
    "feature":"Total freedom with up to 20 m wireless range,Lightweight wireless audio transmission.,Keep playing for up to 29 hours of battery life.,Colourful, reversible suspension headbands are designed for comfort during long play sessions.,Advanced mic filters that make your voice sound richer, cleaner, and more professional. ,Hear every audio cue with breathtaking clarity and get immerse in your game.",
    "brand":"SteelSeries",
    "image":"87.jpg",
},{
    "id":85,
    "title":"Razer Kraken Kitty",
    "feature":"Kitty ears and earcups powered by Razer Chroma,Stream-reactive lighting,Active noise-cancetdng microphone,THX Spatial Audio,Cooling-gel ear cushions",
    "brand":"Razer Kraken",
    "image":"88.jpg",
},{
    "id":86,
    "title":"MFTEK",
    "feature":"Noise Cancellation,Volume Control Gaming Headset with Mic,LED light Over-Ear Headphone,3.5mm Wired,40mm Driver Unit,Double bass",
    "brand":"MFTEK",
    "image":"89.jpg",
},{
    "id":87,
    "title":"HP X1000",
    "feature":"Noise Cancellation,7.1 Surround Sound with Mic,50 mm Drivers, 20 Hours of Battery life",
    "brand":"HP",
    "image":"90.jpg",
},{
    "id":88,
    "title":"JBL Quantum 200",
    "feature":"Noise Cancellation,7.1 Surround Sound with Mic, 50 mm Drivers,20 Hours of Battery life",
    "brand":"JBL",
    "image":"91.jpg",
},{
    "id":89,
    "title":"Logitech G29",
    "feature":"33 Lightspeed ,  Suspension Headband ,Lightsync RGB,Could have used a type-c port for charging.",
    "brand":"Logitech",
    "image":"92.jpg",
},{
    "id":90,
    "title":"ELECTROPRIME",
    "feature":"3.5mm Wired Gaming Headphone,   50mm large drive unit, noise reduction microphone, skin friendly and comfortable ",
    "brand":"Electroprime",
    "image":"93.jpg",
},{
    "id":91,
    "title":"Razer RZ04",
    "feature":"Stream-reactive lighting,Active noise-cancetdng microphone,THX Spatial Audio,Cooling-gel ear cushions",
    "brand":"Razer",
    "image":"94.jpg",
},{
    "id":92,
    "title":"sktome",
    "feature":"Cool LED light, Over-Ear Headphones with Volume Control, Noise Reduction Voice Changer Gaming Headset,Cooling-gel ear cushions",
    "brand":"Sktome",
    "image":"95.jpg",
},{
    "id":93,
    "title":"ASUS Rog Delta",
    "feature":"Detail-rich audio,127Db Signal-to-Noise ratio,Aura Sync RGB LED lighting outshines the competition,Headphones Jack: Usb",
    "brand":"ASUS",
    "image":"96.jpg",
},{
    "id":94,
    "title":"ASUS RGB Gaming",
    "feature":"ROG Delta with Detachable Mic,Hi-Res ESS Quad-DAC,Circular RBG lighting Effect,USB-C Connector for Pcs, Consoles, and Mobile Gaming",
    "brand":"ASUS",
    "image":"97.jpg",
},{
    "id":95,
    "title":"Sennheiser GSP 350",
    "feature":"Dolby 7.1 surround sound to immerse yourself in the game,Professional noise-canceltdng microphone,Volume control on right ear cup provides on-the-fly level adjustment,Lift to mute microphone feature shuts off in game communication",
    "brand":"Sennheiser",
    "image":"98.jpg",
},{
    "id":96,
    "title":"ASUS ROG Fusion II 500",
    "feature":"AI Beamforming Mic,7.1 Surround Sound,Hi-Res ESS 9280 Quad DAC,3.5mm, USB-C",
    "brand":"ASUS",
    "image":"99.jpg",
},{
    "id":97,
    "title":"Razer Kraken V3 Pro ",
    "feature":"Haptic Technology,Triforce Titanium 50mm Drivers,THX Spatial Audio,Hyperspeed Wireless,Hybrid Fabric & Leatherette Memory Foam Cushions",
    "brand":"Razer",
    "image":"100.jpg",
},{
    "id":98,
    "title":"JBL Quantum ONE",
    "feature":" Lightweight(369), Noise Cancellation, Volume-Control, Microphone Feature,Hybrid Fabric & Leatherette Memory Foam Cushions",
    "brand":"JBL",
    "image":"101.jpg",
},{
    "id":99,
    "title":"Razer Barracuda Pro",
    "feature":"Hybrid Active Noise Cancellation Technology, THX Achromatic Audio Amplifier, TriForce Bio-cellulose 50mm DriverMicrophone Feature,  SmartSwitch Dual Wireless",
    "brand":"Razer",
    "image":"102.jpg",
},{
    "id":100,
    "title":"JBL Quantum 800",
    "feature":" Lightweight(410g),Noise Cancellation,Volume-Control,Microphone Feature, SmartSwitch Dual Wireless",
    "brand":"JBL",
    "image":"103.jpg",
},{
    "id":101,
    "title":"Sennheiser HD 820",
    "feature":" Lightweight(508g),Closed, circumaural dynamic stereo, headphones,Natural hearing experience - realistic sound field with minimal resonance,Glass covered ear cups make the transducer visible, Noice cancellation",
    "brand":"Sennheiser",
    "image":"104.jpg",
},{
    "id":102,
    "title":"HiFiMAN Arya Stealth Magnet",
    "feature":" Lightweight(1.5kg),Reducing interference in sound wave transmissions from the diaphragm.,Metal and High-Grade Plastic Construction,high-grade plastic for lightweight comfort and rugged durability, Noice cancellation",
    "brand":"HiFiMAN",
    "image":"105.jpg",
},]